version: '3.8'

services:

  ski-db:
    image: mysql:8.0
    container_name: ski-db
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: r
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql


  kaddem-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ski-app
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ski-db:3306/r?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - ski-db
    networks:
      - app-network


networks:
  app-network:


volumes:
  mysql-data: